# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: flow/execution/execution.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto
import grpclib

from .flow import entities


@dataclass
class PingRequest(betterproto.Message):
    pass


@dataclass
class PingResponse(betterproto.Message):
    pass


@dataclass
class GetAccountAtBlockIDRequest(betterproto.Message):
    block_id: bytes = betterproto.bytes_field(1)
    address: bytes = betterproto.bytes_field(2)


@dataclass
class GetAccountAtBlockIDResponse(betterproto.Message):
    account: entities.Account = betterproto.message_field(1)


@dataclass
class ExecuteScriptAtBlockIDRequest(betterproto.Message):
    block_id: bytes = betterproto.bytes_field(1)
    script: bytes = betterproto.bytes_field(2)
    arguments: List[bytes] = betterproto.bytes_field(3)


@dataclass
class ExecuteScriptAtBlockIDResponse(betterproto.Message):
    value: bytes = betterproto.bytes_field(1)


@dataclass
class GetEventsForBlockIDsResponse(betterproto.Message):
    results: List["GetEventsForBlockIDsResponseResult"] = betterproto.message_field(1)


@dataclass
class GetEventsForBlockIDsResponseResult(betterproto.Message):
    block_id: bytes = betterproto.bytes_field(1)
    block_height: int = betterproto.uint64_field(2)
    events: List[entities.Event] = betterproto.message_field(3)


@dataclass
class GetEventsForBlockIDsRequest(betterproto.Message):
    type: str = betterproto.string_field(1)
    block_ids: List[bytes] = betterproto.bytes_field(2)


@dataclass
class GetTransactionResultRequest(betterproto.Message):
    block_id: bytes = betterproto.bytes_field(1)
    transaction_id: bytes = betterproto.bytes_field(2)


@dataclass
class GetTransactionByIndexRequest(betterproto.Message):
    block_id: bytes = betterproto.bytes_field(1)
    index: int = betterproto.uint32_field(2)


@dataclass
class GetTransactionResultResponse(betterproto.Message):
    status_code: int = betterproto.uint32_field(1)
    error_message: str = betterproto.string_field(2)
    events: List[entities.Event] = betterproto.message_field(3)


@dataclass
class GetTransactionsByBlockIDRequest(betterproto.Message):
    block_id: bytes = betterproto.bytes_field(1)


@dataclass
class GetTransactionResultsResponse(betterproto.Message):
    transaction_results: List[
        "GetTransactionResultResponse"
    ] = betterproto.message_field(1)


@dataclass
class GetRegisterAtBlockIDRequest(betterproto.Message):
    block_id: bytes = betterproto.bytes_field(1)
    register_owner: bytes = betterproto.bytes_field(2)
    # bytes register_controller = 3; @deprecated
    register_key: bytes = betterproto.bytes_field(4)


@dataclass
class GetRegisterAtBlockIDResponse(betterproto.Message):
    value: bytes = betterproto.bytes_field(1)


@dataclass
class GetLatestBlockHeaderRequest(betterproto.Message):
    is_sealed: bool = betterproto.bool_field(1)


@dataclass
class GetBlockHeaderByIDRequest(betterproto.Message):
    id: bytes = betterproto.bytes_field(1)


@dataclass
class BlockHeaderResponse(betterproto.Message):
    block: entities.BlockHeader = betterproto.message_field(1)


class ExecutionAPIStub(betterproto.ServiceStub):
    """ExecutionAPI is the API provided by the execution nodes."""

    async def ping(self) -> PingResponse:
        """Ping is used to check if the access node is alive and healthy."""

        request = PingRequest()

        return await self._unary_unary(
            "/flow.execution.ExecutionAPI/Ping",
            request,
            PingResponse,
        )

    async def get_account_at_block_i_d(
        self, *, block_id: bytes = b"", address: bytes = b""
    ) -> GetAccountAtBlockIDResponse:
        """
        GetAccountAtBlockID gets an account by address at the given block ID
        """

        request = GetAccountAtBlockIDRequest()
        request.block_id = block_id
        request.address = address

        return await self._unary_unary(
            "/flow.execution.ExecutionAPI/GetAccountAtBlockID",
            request,
            GetAccountAtBlockIDResponse,
        )

    async def execute_script_at_block_i_d(
        self, *, block_id: bytes = b"", script: bytes = b"", arguments: List[bytes] = []
    ) -> ExecuteScriptAtBlockIDResponse:
        """
        ExecuteScriptAtBlockID executes a ready-only Cadence script against the
        execution state at the block with the given ID.
        """

        request = ExecuteScriptAtBlockIDRequest()
        request.block_id = block_id
        request.script = script
        request.arguments = arguments

        return await self._unary_unary(
            "/flow.execution.ExecutionAPI/ExecuteScriptAtBlockID",
            request,
            ExecuteScriptAtBlockIDResponse,
        )

    async def get_events_for_block_i_ds(
        self, *, type: str = "", block_ids: List[bytes] = []
    ) -> GetEventsForBlockIDsResponse:
        """
        GetEventsForBlockIDs retrieves events for all the specified block IDs
        that have the given type
        """

        request = GetEventsForBlockIDsRequest()
        request.type = type
        request.block_ids = block_ids

        return await self._unary_unary(
            "/flow.execution.ExecutionAPI/GetEventsForBlockIDs",
            request,
            GetEventsForBlockIDsResponse,
        )

    async def get_transaction_result(
        self, *, block_id: bytes = b"", transaction_id: bytes = b""
    ) -> GetTransactionResultResponse:
        """GetTransactionResult gets the result of a transaction."""

        request = GetTransactionResultRequest()
        request.block_id = block_id
        request.transaction_id = transaction_id

        return await self._unary_unary(
            "/flow.execution.ExecutionAPI/GetTransactionResult",
            request,
            GetTransactionResultResponse,
        )

    async def get_transaction_result_by_index(
        self, *, block_id: bytes = b"", index: int = 0
    ) -> GetTransactionResultResponse:
        """
        GetTransactionResultByIndex gets the result of a transaction at the
        index .
        """

        request = GetTransactionByIndexRequest()
        request.block_id = block_id
        request.index = index

        return await self._unary_unary(
            "/flow.execution.ExecutionAPI/GetTransactionResultByIndex",
            request,
            GetTransactionResultResponse,
        )

    async def get_transaction_results_by_block_i_d(
        self, *, block_id: bytes = b""
    ) -> GetTransactionResultsResponse:
        """
        GetTransactionResultByIndex gets the results of all transactions in the
        block ordered by transaction index
        """

        request = GetTransactionsByBlockIDRequest()
        request.block_id = block_id

        return await self._unary_unary(
            "/flow.execution.ExecutionAPI/GetTransactionResultsByBlockID",
            request,
            GetTransactionResultsResponse,
        )

    async def get_register_at_block_i_d(
        self,
        *,
        block_id: bytes = b"",
        register_owner: bytes = b"",
        register_key: bytes = b"",
    ) -> GetRegisterAtBlockIDResponse:
        """
        GetRegisterAtBlockID collects a register at the block with the given ID
        (if available).
        """

        request = GetRegisterAtBlockIDRequest()
        request.block_id = block_id
        request.register_owner = register_owner
        request.register_key = register_key

        return await self._unary_unary(
            "/flow.execution.ExecutionAPI/GetRegisterAtBlockID",
            request,
            GetRegisterAtBlockIDResponse,
        )

    async def get_latest_block_header(
        self, *, is_sealed: bool = False
    ) -> BlockHeaderResponse:
        """
        GetLatestBlockHeader gets the latest sealed or unsealed block header.
        """

        request = GetLatestBlockHeaderRequest()
        request.is_sealed = is_sealed

        return await self._unary_unary(
            "/flow.execution.ExecutionAPI/GetLatestBlockHeader",
            request,
            BlockHeaderResponse,
        )

    async def get_block_header_by_i_d(self, *, id: bytes = b"") -> BlockHeaderResponse:
        """GetBlockHeaderByID gets a block header by ID."""

        request = GetBlockHeaderByIDRequest()
        request.id = id

        return await self._unary_unary(
            "/flow.execution.ExecutionAPI/GetBlockHeaderByID",
            request,
            BlockHeaderResponse,
        )
